### ISSUE TITLE
Web instance error in sending FMU

### ISSUE THREAD

**Issue by fabianoP** [RichieBrady/SimApi-Python#2]
| django.db.utils.ProgrammingError: column "model_count" of relation "rest_api_fmumodel" does not exist web     | LINE 1: ...umodel" ("model_name", "user_id", "container_id", "model_cou...

proba bly a migration issue?

**Comment by fabianoP** [comment]
I add more info, I tried a lot of solutions this is my latest outcome, still a small issue I don't understand why:
`generator           | ! makeFMULib.py -- Running utility application {util-get-address-size.exe}
generator           | ! makeFMULib.py -- FMU shared library {m123.so} has address size {64}
generator           | ! makeFMULib.py -- Cleaning up intermediate files
generator           | ! EnergyPlusToFMU.py -- Creating zip file {m123.zip}, with compression on
generator           | ! EnergyPlusToFMU.py -- Renaming completed zip file {m123.zip} to {m123.fmu}
generator           | ! EnergyPlusToFMU.py -- Cleaning up intermediate files
generator           | Reading input and weather file for EnergyPlusToFMU program.
generator           | [2020-04-13 05:13:22,161: INFO/ForkPoolWorker-1] Task generator_tasks.gen_fmu[71710ae2-6be9-414f-8fcc-2c45d94c22a8] succeeded in 7.5077952s: 'success'
generator           | 172.28.0.5 - - [13/Apr/2020 05:13:22] "POST /file_upload/m123 HTTP/1.1" 200 15
web                 | [2020-04-13 05:13:22,471: INFO/ForkPoolWorker-1] Task rest_api.tasks.post_model[37ed4346-9bca-449b-ae83-62e8092d1213] succeeded in 8.111909500003094s: 'b\'FMU FILE EXISTS\' : 200'
web                 | FMU Ready
web                 | [13/Apr/2020 05:13:24] "POST /init_model/ HTTP/1.1" 201 296
web                 | Bad Request: /user/
web                 | [13/Apr/2020 05:13:35] "POST /user/ HTTP/1.1" 400 50
web                 | [13/Apr/2020 05:13:35] "POST /login/ HTTP/1.1" 200 52
web                 | [2020-04-13 05:13:35,879: INFO/MainProcess] Received task: rest_api.tasks.send_fmu[5341ac90-7a01-4905-a787-3fba92898728]
web                 | [2020-04-13 05:13:35,880: INFO/ForkPoolWorker-1] rest_api.tasks.send_fmu[5341ac90-7a01-4905-a787-3fba92898728]: send_fmu data {'model_name': 'm123', 'container_id': None, 'model_count': '1', 'step_size': 600, 'final_time': 24.0, 'Authorization': 'ad91db8713ef0806a18e5327f6d94cac2eb3638d'}
generator           | http://src_simulator_1:8000/receive_fmu/m123
generator           | {u'final_time': 24.0, u'container_id': None, u'model_count': u'1', u'step_size': 600, 'isSimOne': True, u'model_name': u'm123', u'Authorization': u'ad91db8713ef0806a18e5327f6d94cac2eb3638d'}
HERE IS THE MAIN PROBLEM :
simulator_1         | Creation of the directory /home/deb/code/fmu_data/m123 failed
simulator_1         | Traceback (most recent call last):
simulator_1         |   File "/home/deb/miniconda/lib/python3.7/site-packages/bottle.py", line 868, in _handle
simulator_1         |     return route.call(**args)
simulator_1         |   File "/home/deb/miniconda/lib/python3.7/site-packages/bottle.py", line 1748, in wrapper
simulator_1         |     rv = callback(*a, **ka)
simulator_1         |   File "./simulator_api/sim_api.py", line 47, in receive_fmu
simulator_1         |     write_json(j_dict, save_path + '/model_params.json')
simulator_1         |   File "./simulator_api/sim_api.py", line 13, in write_json
simulator_1         |     with open(filename, 'w') as f:
simulator_1         | FileNotFoundError: [Errno 2] No such file or directory: '/home/deb/code/fmu_data/m123/model_params.json'
simulator_1         | 172.28.0.7 - - [13/Apr/2020 05:13:35] "POST /receive_fmu/m123 HTTP/1.1" 500 1602
generator           | 500
generator           | 172.28.0.5 - - [13/Apr/2020 05:13:38] "POST /fmu_to_simulator/m123 HTTP/1.1" 200 58
web                 | [2020-04-13 05:13:38,935: INFO/ForkPoolWorker-1] Task rest_api.tasks.send_fmu[5341ac90-7a01-4905-a787-3fba92898728] succeeded in 3.0541693999985s: 'b\'File upload success in sim container for model_name = m123\' | 200'
web                 | [13/Apr/2020 05:13:39] "POST /send_fmu/ HTTP/1.1" 200 69
web                 | [13/Apr/2020 05:13:39] "GET /graphql/ HTTP/1.1" 200 45`

The FMU is created but does not move to the simulator.

**Comment by RichieBrady** [comment]
Hi Fabinao,

That's strange it won't create the directory. Do you have an fmu_data
folder  in the fmu_simulator package? It doesn't look like a permissions
issue, unless all the error output did not get printed.
There are no shared folders in the fmu_simulator and fmu_generator
containers anymore to negate any permission issues. I'm going to push an
update with the shared folder removed for the web container
as well. I think we will be able to get it working today. If you want to
setup a meeting I'm free.

All the best,
Richard

**Comment by fabianoP** [comment]
This is the filesystem of the container:

generator           | [2020-04-13 09:06:18,231: INFO/ForkPoolWorker-1] Task generator_tasks.gen_fmu[712b2a9c-b88e-4f16-9e17-06605659b469] succeeded in 7.9396777s: 'success'
generator           | 172.31.0.5 - - [13/Apr/2020 09:06:18] "POST /file_upload/m12344 HTTP/1.1" 200 15
web                 | [2020-04-13 09:06:18,627: INFO/ForkPoolWorker-1] Task rest_api.tasks.post_model[3bb6f8e4-b42c-4c78-a463-436bb652b57a] succeeded in 14.48190930000419s: 'b\'FMU FILE EXISTS\' : 200'
web                 | FMU Ready
web                 | [13/Apr/2020 09:06:22] "POST /init_model/ HTTP/1.1" 201 298
web                 | Bad Request: /user/
web                 | [13/Apr/2020 09:06:29] "POST /user/ HTTP/1.1" 400 50
web                 | [13/Apr/2020 09:06:29] "POST /login/ HTTP/1.1" 200 52
web                 | [2020-04-13 09:06:29,500: INFO/MainProcess] Received task: rest_api.tasks.send_fmu[c4a01546-8ac6-4df7-81f3-c28575d94789]
web                 | [2020-04-13 09:06:29,502: INFO/ForkPoolWorker-1] rest_api.tasks.send_fmu[c4a01546-8ac6-4df7-81f3-c28575d94789]: send_fmu data {'model_name': 'm12344', 'container_id': None, 'model_count': '1', 'step_size': 600, 'final_time': 24.0, 'Authorization': 'fb3eda5e15e47595e97ba11f9227b302cca276cb'}
generator           | http://src_simulator_1:8000/receive_fmu/m12344
generator           | {u'final_time': 24.0, u'container_id': None, u'model_count': u'1', u'step_size': 600, 'isSimOne': True, u'model_name': u'm12344', u'Authorization': u'fb3eda5e15e47595e97ba11f9227b302cca276cb'}
simulator_1         | /home/deb/code/.empty
simulator_1         | /home/deb/code/run.sh
simulator_1         | /home/deb/code/.DS_Store
simulator_1         | /home/deb/code/__init__.py
simulator_1         | /home/deb/code/requirements.txt
simulator_1         | /home/deb/code/simulator
simulator_1         | /home/deb/code/simulator/simulation_obj.py
simulator_1         | /home/deb/code/simulator/test_simulation_obj.py
simulator_1         | /home/deb/code/simulator_api
simulator_1         | /home/deb/code/simulator_api/sim_api.py
simulator_1         | /home/deb/code/simulation_process.py
simulator_1         | /home/deb/code/fmu_data
simulator_1         | /home/deb/code/Dockerfile
simulator_1         | /home/deb/code/conda_requirements.txt
simulator_1         | /home/deb/code/volume
simulator_1         | Creation of the directory /home/deb/code/fmu_data/m12344 failed
simulator_1         | Traceback (most recent call last):
simulator_1         |   File "/home/deb/miniconda/lib/python3.7/site-packages/bottle.py", line 868, in _handle
simulator_1         |     return route.call(**args)
simulator_1         |   File "/home/deb/miniconda/lib/python3.7/site-packages/bottle.py", line 1748, in wrapper
simulator_1         |     rv = callback(*a, **ka)
simulator_1         |   File "./simulator_api/sim_api.py", line 55, in receive_fmu
simulator_1         |     write_json(j_dict, save_path + '/model_params.json')
simulator_1         |   File "./simulator_api/sim_api.py", line 20, in write_json
simulator_1         |     with open(filename, 'w') as f:
simulator_1         | FileNotFoundError: [Errno 2] No such file or directory: '/home/deb/code/fmu_data/m12344/model_params.json'
simulator_1         | 172.31.0.7 - - [13/Apr/2020 09:06:29] "POST /receive_fmu/m12344 HTTP/1.1" 500 1606
generator           | 500
generator           | 172.31.0.5 - - [13/Apr/2020 09:06:32] "POST /fmu_to_simulator/m12344 HTTP/1.1" 200 60
web                 | [2020-04-13 09:06:32,580: INFO/ForkPoolWorker-1] Task rest_api.tasks.send_fmu[c4a01546-8ac6-4df7-81f3-c28575d94789] succeeded in 3.078060400002869s: 'b\'File upload success in sim container for model_name = m12344\' | 200'
web                 | [13/Apr/2020 09:06:33] "POST /send_fmu/ HTTP/1.1" 200 71
web                 | [13/Apr/2020 09:06:33] "GET /graphql/ HTTP/1.1" 200 47
